
name: Data Updater KL

on:
  push:
    paths:
      - '.github/workflows/data-updater-kl.yml'
      - 'data-scraper-v2alpha.py'
      - 'test.py'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 8 1 * *'

jobs:
  script:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 2
      matrix:
        type: [bungalow]
        state: [kl]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Data scraping and export
      run: python -u test.py
      continue-on-error: true
    - name: Commit & push data updates
      run: |
        git config --local user.name github-actions
        git config --local user.email "action@github.com"
        git pull
        git add data/*.csv
        git add md5hash/*.md5
        if [[ $(git diff-index --cached HEAD) ]]; then
          git commit -m "Monthly data update"
          git tag -a $(date "+v%Y%m%d%H%M%S") -m "Monthly data update"
          git push origin main --follow-tags
        fi
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
    - name: Check File Existence
      run: |
        echo $(ls -1q data/*.csv | wc -l) property datasets detected.
        echo $(ls -1q md5hash/*.md5 | wc -l) MD5 hashes detected.
        if [[ $(ls -1q md5hash/*.md5 | wc -l) != $(ls -1q data/*.csv | wc -l) ]]; then
          echo Scraping incomplete! 
          exit 1
        else
          echo Scraping completed!
        fi
